feat(components): localization for invite embed
skyra-project/discord-components pull request #183
Opened 2021-12-18 16:58 UTC by kaname-png

2021-12-19 06:55 UTC, kyranet approved these changes

2021-12-19 12:05 UTC, favna requested changes
cI failed

2021-12-22 19:45 UTC, favna approved these changes

2021-12-22 19:46 UTC, merged

2021-12-22 19:59 UTC, favna commented
Released in v2..13.0