Add styles for tags within `discord-markdown-description`
skyra-project/discord-components pull request #195
Opened 2022-01-10 02:23 UTC by sunlanterns

Added styles for the html elements that are the basic markdown equivalents of:
inline emoji, inline code, multiline code, blockquote, and spoiler.

Upon closer inspection bold, italic, strikethrough, and underline are all used 'as is' already by discord so no additional styling needed. 
(Originally thought bold was off because it didn't match field titles, but it seems that's just the way discord does things).

Feel free to let me know if the classnames I included are ok or not - I don't have any reason I can't change them. 

I also did a little bit of cleverness around blockquotes to get the line to match discord's but without needing any additional tags, since a plain blockquote tag is all a markdown generator would create. And I did a little bit of extra on spoilers so that you can 'view' the text if you're actively 'mousedown' on the spoiler but without javascript it won't get any closer than that to what discord has.

2022-01-10 20:15 UTC, favna requested changes
I did a few adjustments myself, in particular to how spoilers are rendered because they also have an on hover state. I also added a sample bit to the index.html for dev testing / porting it over later to the codesandboxes. 

That said, I have one more change request for you. Can you also do light mode? For example code blocks and spoilers have different background colors. You can "detect" light theme config through the `.discord-light-theme` class, see `discord-embed.css` for example.

2022-01-12 20:36 UTC, sunlanterns commented
Discord Light colors should be added now!

2022-01-12 20:44 UTC, favna approved these changes

2022-01-12 20:51 UTC, merged

2022-01-12 20:58 UTC, favna commented
Released in [v3.1.0](https://github.com/skyra-project/discord-components/releases/tag/v3.1.0)