add: New arguments in the modal
skyra-project/discord-components pull request #453
Opened 2024-08-20 01:59 UTC by eumarciel404

2024-08-20 02:07 UTC, eumarciel404 commented
I definitely don't know why it gave an error before but maybe it was because I forgot to use "yarn lint"

2024-08-20 16:18 UTC, favna requested changes

2024-08-20 16:18 UTC, favna commented on packages/core/src/components/discord-modal/DiscordModal.ts
> +		const slotedItems = expanderT!.assignedElements();
Do not use `!.` (non null assertions), Unlike `?.` (optional chaining) they are removed when compiled and can lead to unexpected errors being thrown for JavaScript users.

2024-08-20 16:18 UTC, favna commented on packages/core/src/components/discord-input-text/DiscordInputText.ts
> +			dialogElement.addEventListener('close', () => {
Instead of tracking this in a state use connectedCallback and disconnectedCallback to attach it. Better yet, use `@close` on the component itself.

2024-08-22 00:28 UTC, eumarciel404 reviewed
Here I changed the "hasWarning" attribute to public for use in modal class (more for polishing) and added some more specific checks on the character count (again to polishing)

2024-08-24 10:46 UTC, favna approved these changes

2024-08-24 10:46 UTC, merged