Command context menu
skyra-project/discord-components pull request #485
Opened 2024-10-08 04:05 UTC by eumarciel404

2024-10-08 14:51 UTC, eumarciel404 reviewed
Lol, wtf what happened here?

2024-10-19 12:35 UTC, favna requested changes

2024-10-19 12:35 UTC, favna commented on packages/core/src/components/discord-command/DiscordCommand.ts
> +	private readonly validButtonTypes = new Set(['user_command', 'message_command', 'slash_command']);
```suggestion
	private readonly validCommandTypes = new Set(['user_command', 'message_command', 'slash_command']);
```

2024-10-19 12:35 UTC, favna commented on packages/core/src/components/discord-command/DiscordCommand.ts
> +			} else if (!this.validButtonTypes.has(this.type)) {
```suggestion
			} else if (!this.validCommandTypes.has(this.type)) {
```

2024-10-19 12:35 UTC, favna commented on packages/core/src/components/discord-command/DiscordCommand.ts
> +				throw new RangeError("DiscordCommand `type` prop must be one of: 'context_menu', 'slash_command'");
```suggestion
				throw new RangeError("DiscordCommand `type` prop must be one of: 'user_command', 'message_command', or 'slash_command'");
```

2024-10-19 15:07 UTC, favna approved these changes

2024-10-19 15:07 UTC, merged